// <auto-generated />
using BuildAHordeBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildAHordeBE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906002552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildAHordeBE.Models.BattleFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BattleFormationDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BattleFormationKeywords")
                        .HasColumnType("text");

                    b.Property<int?>("BattleFormationPoints")
                        .HasColumnType("integer");

                    b.Property<string>("BattleFormationTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("battleFormations");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.BattleTactic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BattleTacticsAffray")
                        .HasColumnType("text");

                    b.Property<string>("BattleTacticsCard")
                        .HasColumnType("text");

                    b.Property<string>("BattleTacticsDomination")
                        .HasColumnType("text");

                    b.Property<string>("BattleTacticsTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("battleTactics");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Faction", b =>
                {
                    b.Property<int>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactionId"));

                    b.Property<string>("FactionAlliance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FactionId");

                    b.ToTable("factions");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Manifestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManifestationPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ManifestationTitle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("manifestations");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Prayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<string>("PrayerSpells")
                        .HasColumnType("text");

                    b.Property<string>("PrayerTitle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("prayers");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.SpellLore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<string>("SpellLoreSpells")
                        .HasColumnType("text");

                    b.Property<string>("SpellLoreTitle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("spellLores");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.BattleFormation", b =>
                {
                    b.HasOne("BuildAHordeBE.Models.Faction", "Faction")
                        .WithMany("BattleFormations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.BattleTactic", b =>
                {
                    b.HasOne("BuildAHordeBE.Models.Faction", "Faction")
                        .WithMany("BattleTactics")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Manifestation", b =>
                {
                    b.HasOne("BuildAHordeBE.Models.Faction", "Faction")
                        .WithMany("Manifestations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Prayer", b =>
                {
                    b.HasOne("BuildAHordeBE.Models.Faction", "Faction")
                        .WithMany("Prayers")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.SpellLore", b =>
                {
                    b.HasOne("BuildAHordeBE.Models.Faction", "Faction")
                        .WithMany("SpellLores")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("BuildAHordeBE.Models.Faction", b =>
                {
                    b.Navigation("BattleFormations");

                    b.Navigation("BattleTactics");

                    b.Navigation("Manifestations");

                    b.Navigation("Prayers");

                    b.Navigation("SpellLores");
                });
#pragma warning restore 612, 618
        }
    }
}
